name: Appium Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install Git LFS
        run: sudo apt-get install git-lfs

      - name: Pull LFS files
        run: git lfs pull

      - name: Move APK to correct location
        run: mv booking-com-32-9.apk src/test/resources/apps/booking-com-32-9.apk

      - name: Set up Maven
        run: |
          wget https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          tar xzvf apache-maven-3.9.6-bin.tar.gz
          echo "M2_HOME=$HOME/apache-maven-3.9.6" >> $GITHUB_ENV
          echo "PATH=$HOME/apache-maven-3.9.6/bin:$PATH" >> $GITHUB_ENV

      - name: Run tests
        run: mvn test