name: Appium Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install Git LFS
        run: sudo apt-get install git-lfs

      - name: Pull LFS files
        run: git lfs pull

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.6.2'

      - name: Install Appium
        run: npm install -g appium

      - name: Download Android SDK
        run: wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip

      - name: Unzip Android SDK
        run: unzip sdk-tools-linux-4333796.zip -d $HOME/android-sdk

      - name: Set Android environment variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/tools/bin" >> $GITHUB_PATH

      - name: Create and start Android emulator
        run: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-30;google_apis;x86"
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n pixel_3a -k "system-images;android-30;google_apis;x86"
          $ANDROID_HOME/emulator/emulator -avd pixel_3a -no-window &
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 10; done; input keyevent 82'

      - name: Set up Maven
        run: |
          wget https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          tar xzvf apache-maven-3.9.6-bin.tar.gz
          echo "M2_HOME=$HOME/apache-maven-3.9.6" >> $GITHUB_ENV
          echo "PATH=$HOME/apache-maven-3.9.6/bin:$PATH" >> $GITHUB_ENV

      - name: Run tests
        run: mvn test